### ISSUE TITLE
bandjoin error: supplied resource is not a valid GObject resource

### ISSUE THREAD

**Issue by kleisauke** [jcupitt/php-vips#10]
Testcase: https://gist.github.com/kleisauke/a84c4a734f1e8636f045fbee6554de8f

`php test.php input.jpg output.jpg`

Produces these errors:
```
PHP Warning:  vips_call(): supplied resource is not a valid GObject resource in /var/www/vendor/jcupitt/vips/src/Image.php on line 359
PHP Warning:  vips_call(): supplied resource is not a valid GObject resource in /var/www/vendor/jcupitt/vips/src/Image.php on line 359
Segmentation fault (core dumped)
```

If we replace the `bandjoin` function with: `$image->bandjoin(255);` then the script doesn't return any errors. Couldn't find the underlying problem of this.

Also spotted a bug in the `bandsplit` function ([line 791](https://github.com/jcupitt/php-vips/blob/master/src/Image.php#L791)). The interpunct should be a comma:
```php
$result[] = $this->extract_band($i, $options); 
```

**Comment by jcupitt** [comment]
I made a dev branch which seems to fix this (I think). If I run your gist like this:

```
$ php testcase.php ~/pics/k2.jpg x.jpg
```

I see the picture with a circular mask.

**Comment by jcupitt** [comment]
Also, thank you very much for looking at this, @kleisauke, it's really good to have someone who knows about PHP on the job. 

What do you think about the API? It's very close to the Ruby and Python interfaces, but maybe not so PHP-ish? I don't really know.

**Comment by kleisauke** [comment]
@jcupitt 
Still getting the same error (different line number, same function):
```
PHP Warning:  vips_call(): supplied resource is not a valid GObject resource in /var/www/t0.nl/vendor/jcupitt/vips/src/Image.php on line 375
PHP Warning:  vips_call(): supplied resource is not a valid GObject resource in /var/www/t0.nl/vendor/jcupitt/vips/src/Image.php on line 375
Segmentation fault (core dumped)
```

Versions used:
```
PHP 7.0.8-0ubuntu0.16.04.2 (cli) ( NTS )
vips-8.4.1-Fri Sep 30 13:47:08 CEST 2016
php-vips dev branch
```

I can try to update my PHP to the latest version and see what happens.

About the API:
I don't have much experience with designing API's. But I think it currently looks fine (directly calling libvips operators is great). You may take look at other PHP Image API's to see how they solve things (for example [Intervention Image](http://image.intervention.io/)).

By the way,
We intend to use this library in the future for our [image cache & resize proxy](https://github.com/andrieslouw/imagesweserv). Most of our old PHP image processing code that we coded with the GD/Imagick library have already been converted to the new PHP bindings for libvips (see https://github.com/andrieslouw/imagesweserv/commit/b377fe7ada439fa692ef3a7f515f242f53e940cc). However some of the functions that are in libvips are missing in the PHP bindings:
- Matrix creations such as: `vips_image_new_matrixv` (or `Image::new_matrixv`). We use those for sepia filters and sharpen functions.
- `vips_image_get_typeof` (or `$image->get_typeof`) and `vips_image_set_string` or (`$image->set`). To override/remove EXIF orientation data or to set the scale of a matrix.
- `$image->sRGB2XYZ()->XYZ2Lab()->Lab2LCh()` and `$image->LCh2Lab()->Lab2XYZ()->XYZ2sRGB()`. To move colour spaces from and back to sRGB for editing lightness, chroma or hue. (Not sure if `$image->colourspace("xyz")->colourspace("lab")->colourspace("lch")` is the same)

**Comment by kleisauke** [comment]
Just updated PHP to 7.0.11 and this issue is gone. It can be useful to change the minimal PHP version to 7.0.11 in [composer.json](https://github.com/jcupitt/php-vips/blob/master/composer.json#L20).

Should I close this issue?

**Comment by jcupitt** [comment]
OK, I've tagged minimum php as 7.0.11 in `dev`. Yes, let's close.

**Comment by jcupitt** [comment]
Ooop, sorry, on your questions:

* You can use `Vips\newFromArray([[1,2,3],[4,5,6]])`. It has a couple of extra params to set scale and offset. You can also use array constants directly, for example: `$image->add([[1, 2, 3], [4, 5, 6]])` will make a 3x2 image and add that to `$image`. You can't set scale and offset on image constants like this though.
* You can use any vips property directly from PHP, for example `$image->exif_data` will fetch all the exif data from an image. At least, I think it will, I hope it does `-` -> `_` conversion for you. 
* You can just do `$image->colourspace("lch")` and it'll find the best sequence of colourspace conversions to take you from the current colourspace into LCh.

I like your image proxy, it looks fun!

**Comment by jcupitt** [comment]
This works for property acccess:

```
    $name = "exif-data";
    $exif = $image->$name;
```

But it's very clumsy. What would be better? How about `$image->get("exif-data")`?

**Comment by jcupitt** [comment]
... OK, get/set added, and a test for exif access.

**Comment by jcupitt** [comment]
Things like `draw_circle` work now, so you could try that instead of your `mask_ideal` trick.

Use them like this:

```
        $image = Vips\Image::black(100, 100);
        $image = $image->draw_circle(255, 50, 50, 20, ["fill" => true]);
```

The args to draw_circle are ink, centre x, centre y, radius. It should be much faster than `mask_ideal` as well.
