### ISSUE TITLE
ifthenelse error when $options parameter is given

### ISSUE THREAD

**Issue by kleisauke** [jcupitt/php-vips#11]
Testcase: https://gist.github.com/kleisauke/87bda855b86152004b21a3bd0d70caba

`php testcase.php PNG_transparency_demonstration_1.png output.png`

```
PHP Warning:  vips_call() expects parameter 2 to be array, boolean given in /var/www/vendor/jcupitt/vips/src/Image.php on line 375
PHP Fatal error:  Uncaught Error: Call to a member function writeToFile() on null in /var/www/public_html/test.php:9
Stack trace:
#0 {main}
  thrown in /var/www/public_html/test.php on line 9
```

Fix:
In the `ifthenelse` function (line [892](https://github.com/jcupitt/php-vips/blob/master/src/Image.php#L892)):
Change this:
```php
return self::call(
    "ifthenelse", $this, array_merge([$then, $else], $options)
);
```

to: 
```php
return self::call(
    "ifthenelse", $this, array_merge([$then, $else]), $options
);
```

Maybe there are more `array_merge` with `$options` errors. See line [379](https://github.com/jcupitt/php-vips/blob/master/src/Image.php#L379), [383](https://github.com/jcupitt/php-vips/blob/master/src/Image.php#L383) and maybe [771-774](https://github.com/jcupitt/php-vips/blob/master/src/Image.php#L771-L774).

**Comment by jcupitt** [comment]
OK, fixed that one, but you're right, I think most of the `array_merge()` calls need checking. Let's leave this open until they are all tested.

**Comment by kleisauke** [comment]
Whoops: "Method call used 4 parameters, but method signature uses 3 parameters" sorry that I missed that one. Maybe we need [Variable-length argument lists](http://php.net/manual/en/functions.arguments.php#functions.variable-arg-list) for the call function.

**Comment by jcupitt** [comment]
OK, I think this is done. I had to add an extra path for __call() to use, since that has the options baked into the arg list.
