### ISSUE TITLE
fix packaging

### ISSUE THREAD

**Issue by jcupitt** [jcupitt/php-vips#2]
It's unclear how we should package this, it has some C parts and some PHP parts. It might be necessary to split it into a pure-PHP PEAR package and a pure-C PECL package.

**Comment by rexxars** [comment]
Splitting into a C pecl package and distributing the PHP parts through Composer should be enough - I see you've already added a `composer.json`, so I guess you're already on that track.

I think the "de-facto" way of depending on the C package is to add `ext-vips` as a dependency - see https://getcomposer.org/doc/02-libraries.md#platform-packages.

Let me know if/how I can help out.

**Comment by jcupitt** [comment]
Thanks, yes, I'd love some help. 

I've made a base extension here:

https://github.com/jcupitt/php-vips-base

Should that be called `vips-ext` then? 

I'm having trouble packaging it for PECL. The guides I can find seem to recommend using pyrus, but that seems to not work with php7. I don't suppose you know about this stuff?

**Comment by jcupitt** [comment]
For example, I see:

```
$ php /home/john/packages/php/pyrus.phar make
Pyrus version 2.0.0a4 SHA-1: 72271D92C3AA1FA96DF9606CD538868544609A52
Using PEAR installation found at /home/john/vips/php/pear
The "make" command is in the developer tools.  Install developer tools?
Please choose:
  yes
  no
[no] : yes

Warning: Illegal string offset 'c' in phar:///home/john/packages/php/pyrus.phar/Pyrus-2.0.0a4/php/Pyrus/Channel/RemotePackage.php on line 486
... etc.
```

And pyrus seems rather dead, it's not been updated in ages and there are few packages using it. What's the recommended way to package extensions for pecl?

**Comment by jcupitt** [comment]
I just tried php-7.0.11, same problem.

**Comment by rexxars** [comment]
I don't know much about packaging native extensions, so I can't help much there, unfortunately.

It seems like [php-memcached](https://github.com/php-memcached-dev/php-memcached) (just to draw from a random php extension I've used) is using a `package.xml` along with [pear package](https://github.com/php-memcached-dev/php-memcached/blob/master/.travis/travis.sh#L116-L135). Not sure if this is the "de-facto" way of doing it, though.

**Comment by jcupitt** [comment]
I tried with php 7.0.8 as packaged for ubuntu, and that also fails. 

I think (though really I've no clue) I need pyrus.phar to generate the `package.xml` file, and to put the pear package together. I'll have a look at memcached, thanks!

**Comment by jcupitt** [comment]
I think they are still using pear, rather than pear2. Maybe pear2 is dead and everyone just stuck with pear? I'll try that. 

https://github.com/php-memcached-dev/php-memcached/blob/master/.travis/travis.sh#L115

Looks like plain pear, I think.

**Comment by jcupitt** [comment]
OK, the native extension seems to be packaged! It at least sort-of works:

https://github.com/jcupitt/php-vips-ext

```
$ pear package
Package vips-0.1.0.tgz done
$ pear install vips-0.1.0.tgz 
.... installs!
```

Next this repo needs packaging for Composer. 

I don't suppose you know what might be causing the phpDoc problems?

**Comment by jcupitt** [comment]
OK, all packaged, I think.
