### ISSUE TITLE
Repeated operations and memory

### ISSUE THREAD

**Issue by mhirsch** [jcupitt/php-vips#24]
I may be abusing vips with this application, so I apologize if this sounds a little odd. What I would like to do is create a vips pipeline that implements an iterative image processing algorithm, where a number of operations are executed repeatedly on the same image buffer. The problem I'm facing is that under some conditions the amount of memory used by vips explodes. I'd like to understand if this kind of thing is possible entirely within the vips pipeline or whether I have to run each iteration of the algorithm as a separate vips pipeline (e.g. write to a buffer inside the loop, below).

The algorithm itself is a little more complicated that what I'm showing here but this illustrates the problem I'm having. I'm using the C++ API.

In this example, an image is read in and repeated convolution is performed. Vips handles this very nicely and I get the expected result:

```
VImage in = VImage::new_from_file(input,VImage::option()->set( "access", VIPS_ACCESS_SEQUENTIAL ) );

in = in.cast(VIPS_FORMAT_FLOAT);

for(int i=0;i<50;i++) {
  in = in.conv(kernel);
}

in.pngsave("out.png");
```

In this example the memory usage increases until the processes is killed:

```
VImage in = VImage::new_from_file(input,VImage::option()->set( "access", VIPS_ACCESS_SEQUENTIAL ) );

in = in.cast(VIPS_FORMAT_FLOAT);

for(int i=0;i<50;i++) {
  in = in - in.conv(kernel);
}

in.pngsave("out.png");
```

**Comment by mhirsch** [comment]
I'm sorry -- this issue is in the wrong place. I'm going to close it and submit it in the correct place!

**Comment by jcupitt** [comment]
No problem. Answered here: https://github.com/jcupitt/libvips/issues/556
