### ISSUE TITLE
Bad changelog

### ISSUE THREAD

**Issue by remicollet** [jcupitt/php-vips#28]
See https://pecl.php.net/package-changelog.php?package=vips

All versions have:` - First stable release.`

Indeed you correctly add each new release as `<release>` in `<changelog>`, but pecl web site only takes the `<notes>` in the top part.

**Comment by jcupitt** [comment]
Ah OK, I thought the notes were API notes rather than a changelog. I'll try and fix this for 1.0.4. Thanks!

**Comment by jcupitt** [comment]
OK, fixed in 1.0.4. Thanks!
