### ISSUE TITLE
VipsOperation: class "thumbnail_buffer" not found

### ISSUE THREAD

**Issue by leigeber** [jcupitt/php-vips#30]
I apologize if I'm overlooking something obvious here but I can't figure out why I am getting the following error.

```
[Jcupitt\Vips\Exception]
VipsOperation: class "thumbnail_buffer" not found


Exception trace:
 () at /home/vagrant/importer/vendor/jcupitt/vips/src/Image.php:635
 Jcupitt\Vips\Image::errorVips() at /home/vagrant/importer/vendor/jcupitt/vips/src/Image.php:656
 Jcupitt\Vips\Image::errorIsArray() at /home/vagrant/importer/vendor/jcupitt/vips/src/Image.php:904
 Jcupitt\Vips\Image::callBase() at /home/vagrant/importer/vendor/jcupitt/vips/src/Image.php:996
 Jcupitt\Vips\Image::__callStatic() at /home/vagrant/importer/app/Handlers/ImageHandler.php:81
...
```

The call in question is straight forward and other Vips methods are working as expected.

```
$thumb = Vips\Image::thumbnail_buffer($buffer, 500);
```

Any suggestions? Thanks!

**Comment by jcupitt** [comment]
Hi @leigeber, sorry, `thumbnail_buffer` is part of vips 8.5, due in March. The online docs have the operation already, but your libvips won't.

You can build libvips from git master if you need it now, or just use `resize` in the meantime.

**Comment by jcupitt** [comment]
I've regenerated the autodocs and made sure they are for 8.4 now. Sorry for the confusion and thanks for pointing out this dumbness.
