### ISSUE TITLE
php-vips 1.0.4 errors out 

### ISSUE THREAD

**Issue by mnglkhn** [jcupitt/php-vips#31]
Hi, 

I have installed vips 8.4  and when I try to install php-vips 1.0.4 it dies out with this message: 

**"configure: error: you need at least vips 8.2 for this module "**

**Comment by jcupitt** [comment]
Hello, that's asking about the libvips version. What version of libvips do you have installed?

I'll try to improve the wording.

**Comment by mnglkhn** [comment]
I have libvips in /usr/local/lib/libvips.so, along with libvips.la  and libvips.a 

I assume it was installed with vips 8.4 since I have not manually installed it.

**Comment by jcupitt** [comment]
It sounds like you are missing the headers and the .pc file. Do you have `/usr/local/include/vips`?

**Comment by mnglkhn** [comment]
I just checked and the dir with all header files is there.

**Comment by jcupitt** [comment]
Then maybe you've not set `PKG_CONFIG_PATH`? This is the environment variable used to find .pc files, and .pc files are the things used to find headers.

Check you have `vips.pc` in `/usr/local/lib/pkgconfig`, check that that directory is on your config path, then try:

```
$ pkg-config vips --modversion
8.5.0
```

To verify that the headers can be found.

**Comment by jcupitt** [comment]
Oops, didn't mean to close.

**Comment by mnglkhn** [comment]
**vips.pc** is listed in **/usr/local/lib/pkgconfig**
along with  **vips-cpp.pc** and **vipsCC.pc**

pkg-config vips --modversion
 does not produce an output

**Comment by jcupitt** [comment]
OK, so you need to set `PKG_CONFIG_PATH`. 

```
$ export PKG_CONFIG_PATH="/usr/local/lib/pkgconfig:$PKG_CONFIG_PATH"
```

You could add that to your `.bashrc`, it's probably useful elsewhere.

**Comment by mnglkhn** [comment]
that did it!

super thanks!

**Comment by jcupitt** [comment]
Great!

**Comment by kleisauke** [comment]
FYI: Currently libvips isn't in any Centos repository. There is package request to get it into the EPEL, see: https://bugzilla.redhat.com/1189137

If you're running Centos >= 7 then there's an easier way to install libvips ([v8.4.4](http://rpms.famillecollet.com/enterprise/7.3/safe/x86_64/repoview/vips.html)) and the PHP vips ([v1.0.4](http://rpms.famillecollet.com/enterprise/7.3/php71/x86_64/repoview/php-pecl-vips.html)) extension (the [Remi repository](http://rpms.famillecollet.com/) provides a easy way to install it).

```shell
# Install the EPEL repository configuration package:
yum install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm

# Install the Remi repository configuration package:
yum install http://rpms.remirepo.net/enterprise/remi-release-7.rpm

# Install the yum-utils package (for the yum-config-manager command):
yum install yum-utils

# Command to enable the repository (PHP 7.1.1, for PHP 7.0.15 use: remi-php70):
yum-config-manager --enable remi-php71

# Install libvips and the PHP vips extension:
yum install php-pecl-vips
```

**Comment by mnglkhn** [comment]
Super nice this install guide for CentOS. 
I had to manually install from source vips. 
Once I did in ~/.bashrc 
$ export PKG_CONFIG_PATH="/usr/local/lib/pkgconfig:$PKG_CONFIG_PATH" 
things went ok 


pecl install vips 

composer require jcupitt/vips

**Comment by airqb** [comment]
Hello there, I am trying to use VIPS in golang in fact it was working fine but not anymore after update golang, I try many ways but still getting this message 

`GOROOT=/Users/qbgrow/go/go1.13.4 #gosetup
GOPATH=/Users/qbgrow/go #gosetup
/Users/qbgrow/go/go1.13.4/bin/go build -o /private/var/folders/gt/y155t_6j50sf5f55b1qqvh8r0000gn/T/___go_build_VueghostApiServer_go /Users/qbgrow/go/src/vueghost-api-server/VueghostApiServer.go #gosetup
# pkg-config --cflags  -- vips vips vips vips vips vips vips vips vips
Package libffi was not found in the pkg-config search path.
Perhaps you should add the directory containing `libffi.pc'
to the PKG_CONFIG_PATH environment variable
Package 'libffi', required by 'gobject-2.0', not found
pkg-config: exit status 1`

**Comment by jcupitt** [comment]
Sorry, you'd need to ask the project maintaining the go binding.
