### ISSUE TITLE
libvips info in phpinfo()

### ISSUE THREAD

**Issue by kleisauke** [jcupitt/php-vips#32]
To check which version of libvips we're running and which loaders are currently enabled, it would be nice to have some more info about the current vips setup in `phpinfo()`. 

For example this is what the GD extension on our server displays:
![gd-phpinfo](https://cloud.githubusercontent.com/assets/12746591/22856432/8f32d3dc-f091-11e6-8464-9ba588511a94.png)
_(Extension source can be found [here](https://github.com/php/php-src/blob/PHP-7.1.1/ext/gd/gd.c#L1200))_

For the vips extension we could do something like this:
![vips-phpinfo](https://cloud.githubusercontent.com/assets/12746591/22856454/dcd4fd72-f091-11e6-815c-716fb23cc987.png)
_(Approximately the same as what you see if you build libvips. I think some info is unnecessary)_

**Comment by jcupitt** [comment]
Here's the equivalent code in php-vips-ext:

https://github.com/jcupitt/php-vips-ext/blob/master/vips.c#L1728

It could certainly be expanded, I agree. Let's tag this as an enhancement.

**Comment by jcupitt** [comment]
I had a quick hack in this branch:

https://github.com/jcupitt/php-vips-ext/tree/better-php-info

`php -i` now shows:

```
vips

vips support => enabled
Major version => 8
Minor version => 5
Micro version => 0
SIMD support with liborc => yes
JPEG support => yes
PNG support => yes
TIFF support => yes
GIF support => yes
OpenEXR support => yes
load OpenSlide => yes
load Matlab => yes
load PDF => yes
load SVG => yes
FITS support => yes
WebP support => yes
load with libMagick => yes
Text rendering support => yes
ICC profile support with lcms => yes
```

libvips doesn't track the versions of libraries it uses, so yes/no is all we can say at the moment. Is that enough?

**Comment by kleisauke** [comment]
I think this will be enough for now. We can expand the info in the future (like environment variables such as `VIPS_DISC_THRESHOLD` or current cache/concurrency settings). Versions of libraries that libvips uses is maybe unnecessary.

Outside the scope of this enhancement, but a nice feature to have, is to change libvips/php-vips settings in the `php.ini` (like [GD](http://php.net/manual/en/image.configuration.php) does). Not sure how difficult this is to implement.

**Comment by jcupitt** [comment]
OK, merged to master. Thanks!

Yes, make another enhancement for settings in `php.ini`.
