### ISSUE TITLE
Image format tagged as uint (should be uchar)

### ISSUE THREAD

**Issue by kleisauke** [jcupitt/php-vips#34]
~~Not sure if this is a libvips problem or libMagick problem; if a multi-size `.ico` is loaded it looks like it will always get the `16x16` format, even if it not exits (like [this one](http://www.google.nl/favicon.ico)). That picture is now returning black in our test environment.~~ My (quick) analysis were wrong, the `16x16` format does exits. See https://github.com/jcupitt/php-vips/issues/34#issuecomment-282010710 for the "real" problem.

Our test environment:
This works: https://imagetest.weserv.nl/?url=icofx.ro/favicon.ico
This doesn't work: https://imagetest.weserv.nl/?url=google.nl/favicon.ico

**Comment by kleisauke** [comment]
Update:
It seems this is a ImageMagick 6.9.7 problem (provided by the [Remi repository](http://rpms.famillecollet.com/enterprise/7.3/safe/x86_64/repoview/vips.html)). Because when I compile libvips 8.4.5 with GraphicsMagick 1.3.25 it's fixed, see our second test environment:
http://t0.nl/?url=google.nl/favicon.ico

**Comment by jcupitt** [comment]
Hi Kleis, these two links:

https://imagetest.weserv.nl/?url=google.nl/favicon.ico
http://t0.nl/?url=google.nl/favicon.ico

are PNGs for me, do you have the original .ico files handy?

Yes, libvips does nothing special for .ico files, it just calls MagickCore, so I'd expect the problem to be there.

**Comment by kleisauke** [comment]
Hi John,

Sorry for the confusion, the original `.ico` file can be found here:
http://www.google.nl/favicon.ico

We are converting them to `.png` because there's no save via libMagic. 

Closing this issue because it's not a libvips/php-vips problem. Will report a bug at ImageMagick if I found the underlying cause of this issue.

**Comment by kleisauke** [comment]
@jcupitt Argh, looks like this particular `.ico` is wrong tagged as `VIPS_FORMAT_UINT` in the libvips magick loader which caused that the image is returning black. I was wrong about that the `16x16` format does not exits, see:
```bash
identify favicon.ico
favicon.ico[0] ICO 16x16 16x16+0+0 32-bit sRGB 5.43KB 0.000u 0:00.001
favicon.ico[1] ICO 32x32 32x32+0+0 32-bit sRGB 5.43KB 0.000u 0:00.004
```

Tried to cast the image to `VIPS_FORMAT_UCHAR` (`$image->cast(BandFormat::UCHAR)`) but that doesn't work. If I compile with GraphicsMagick instead then this issue is gone and the image is tagged as `VIPS_FORMAT_UCHAR`.

With ImageMagick6:
```
{"width":16,"height":16,"bands":4,"format":"uint","interpretation":"srgb"}
```

With GraphicsMagick:
```
{"width":16,"height":16,"bands":4,"format":"uchar","interpretation":"srgb"}
```

Environment which it fails:
```
libvips 8.4.4
ImageMagick6 6.9.7-6 Q16 (without HDRI)
```

Also fails with the latest libvips source ([f84825a](https://github.com/jcupitt/libvips/commit/f84825a6349f329f44c2b2cd2cf4de0af5d77290)) and a older ImageMagick version:
```
libvips f84825a
ImageMagick 6.7.8-9 Q16 (also without HDRI)
```

Should I reopen this issue?

**Comment by jcupitt** [comment]
Sure, let's reopen, it sounds like a vips bug.

**Comment by jcupitt** [comment]
Sure, let's reopen, it sounds like a vips bug.

**Comment by jcupitt** [comment]
The problem seems to be that `image->depth` for http://www.google.nl/favicon.ico is 32 (????), you have to call `GetImageDepth()` to get the correct value of 8.

Unfortunately, `GetImageDepth()` does not work for other formats. For example, a 16-bit DICOM is reported as depth 1. 

I'll try changing it to `GetImageChannelDepth(AllChannels)`. Hopefully graphicsmagick supports this call.

**Comment by kleisauke** [comment]
Not tested by myself, but it looks like GraphicsMagick will support `GetImageChannelDepth` if I look at the [API docs](http://www.graphicsmagick.org/api/channel.html#getimagechanneldepth
). I will test it out with GraphicsMagick and ImageMagick if this enhancement has been added to libvips.

I can confirm that ImageMagick returns 32 (`32/8-bit`) as depth, see this output (`identify -verbose favicon.ico > favicon-google.txt`):
```
Image: favicon.ico
  Format: ICO (Microsoft icon)
  Class: DirectClass
  Geometry: 16x16+0+0
  Resolution: 72x72
  Print size: 0.222222x0.222222
  Units: Undefined
  Type: PaletteAlpha
  Endianess: Undefined
  Colorspace: sRGB
  Depth: 32/8-bit
  Channel depth:
    red: 8-bit
    green: 8-bit
    blue: 8-bit
    alpha: 8-bit
```

I also did the same `identify` command on [this favicon](http://icofx.ro/favicon.ico):
```
Image: favicon2.ico
  Format: ICO (Microsoft icon)
  Class: DirectClass
  Geometry: 16x16+0+0
  Resolution: 72x72
  Print size: 0.222222x0.222222
  Units: Undefined
  Type: PaletteAlpha
  Endianess: Undefined
  Colorspace: sRGB
  Depth: 4/8-bit
  Channel depth:
    red: 8-bit
    green: 8-bit
    blue: 8-bit
    alpha: 1-bit
```

Attachment: full results of the above `identify` commands.

[favicons test.zip](https://github.com/jcupitt/php-vips/files/797534/favicons.test.zip)

**Comment by jcupitt** [comment]
OK, it works for that google ico file now, and seems to compile at least with current GM. It's not clear how far backwards it can go, or if other file types will break :-(

Anyway, thanks for reporting this crazy thing.

**Comment by kleisauke** [comment]
Just tested with GraphicsMagick and ImageMagick. Both are now working and we're not seeing any black images anymore. Also did some tests with other *magick file formats and couldn't find any problems indicating that the image depth is wrong. I will report it if we are seeing something (crazy) like this. 😄 

Thanks John! I look forward to libvips 8.5. 👍
