### ISSUE TITLE
vips_getpoint gives wrong values for optimized PNG

### ISSUE THREAD

**Issue by kleisauke** [jcupitt/php-vips#36]
It looks like there's someting wrong with the `vips_getpoint` operation when this is performed on an optimized (possible `pngcrush`'d) PNG image.

Test images:
[test_images.zip](https://github.com/jcupitt/php-vips/files/834359/test_images.zip)

Test script:
```php
<?php

require __DIR__ . '/vendor/autoload.php';

use Jcupitt\Vips;

$imageWorking = Vips\Image::newFromFile(__DIR__ . '/PNG_transparency_demonstration_1_20170225194941.png', ['access' => 'random']);
echo (string) $imageWorking . PHP_EOL;
print_r($imageWorking->getpoint(0, 0));

$imageBroken = Vips\Image::newFromFile(__DIR__ . '/PNG_transparency_demonstration_1.png', ['access' => 'random']);
echo (string) $imageBroken . PHP_EOL;
print_r($imageBroken->getpoint(0, 0));
```

Output:
```
{"width":800,"height":600,"bands":4,"format":"uchar","interpretation":"srgb"}
Array
(
    [0] => 255
    [1] => 255
    [2] => 255
    [3] => 0
)
{"width":800,"height":600,"bands":4,"format":"uchar","interpretation":"srgb"}
Array
(
    [0] => 0
    [1] => 0
    [2] => 0
    [3] => 0
)
```

**Comment by jcupitt** [comment]
Hi, `getpoint` is working, the images really are different. `pngcrush` puts 255, 255, 255 into all the fully-transparent parts of the image in the hope that it'll make life easier for the compressor. If you drop the alpha channel from your two images you see this:

![x2](https://cloud.githubusercontent.com/assets/580843/23804992/04730162-05b4-11e7-939c-b7b255b23888.jpg)
![x](https://cloud.githubusercontent.com/assets/580843/23805003/1319e6ea-05b4-11e7-9a0b-125b7f90b62b.jpg)

**Comment by kleisauke** [comment]
I see, so `getpoint` is not the bottle neck here. How about this test case? (trim function [from Python](https://gist.github.com/jcupitt/eecd6d24692c388799e5) converted to PHP):

```php
<?php

require __DIR__ . '/vendor/autoload.php';

use Jcupitt\Vips;

$trim = function (Vips\Image $image, int $sensitivity): Vips\Image {
    $background = $image->getpoint(0, 0);
    // TODO: Forcing background doesn't work
    //$background = [255.0, 255.0, 255.0, 0.0];

    // Pixel interpretation
    $interpretation = $image->interpretation;

    // Scale up 8-bit values to match 16-bit input image
    $multiplier = $interpretation === 'rgb16' || $interpretation === 'grey16' ? 256 : 1;

    // we need to smooth the image, subtract the background from every pixel, take
    // the absolute value of the difference, then threshold
    $mask = $image->median(3)->subtract($background)->abs()->more($sensitivity * $multiplier);

    // sum mask rows and columns, then search for the first non-zero sum in each
    // direction
    $project = $mask->project();

    $profileLeft = $project['columns']->profile();
    $profileRight = $project['columns']->fliphor()->profile();
    $profileTop = $project['rows']->profile();
    $profileBottom = $project['rows']->flipver()->profile();

    // TODO: It goes here wrong. min() for the `broken image` returns 0
    $left = (int)floor($profileLeft['rows']->min());
    $right = $project['columns']->width - (int)floor($profileRight['rows']->min());

    $top = (int)floor($profileTop['columns']->min());
    $bottom = $project['rows']->height - (int)floor($profileBottom['columns']->min());

    $width = $right - $left;
    $height = $bottom - $top;

    return $image->crop($left, $top, $width, $height);
};

$trimSensitivity = 10;

$imageWorking = Vips\Image::newFromFile(__DIR__ . '/PNG_transparency_demonstration_1_20170225194941.png', ['access' => 'random']);
echo 'Before:' . PHP_EOL;
echo (string)$imageWorking . PHP_EOL;
echo 'After:' . PHP_EOL;
echo (string)$trim($imageWorking, $trimSensitivity) . PHP_EOL . PHP_EOL;

$imageBroken = Vips\Image::newFromFile(__DIR__ . '/PNG_transparency_demonstration_1.png', ['access' => 'random']);
echo 'Before:' . PHP_EOL;
echo (string)$imageBroken . PHP_EOL;
echo 'After:' . PHP_EOL;
echo (string)$trim($imageBroken, $trimSensitivity) . PHP_EOL;
```

Output:
```
Before:
{"width":800,"height":600,"bands":4,"format":"uchar","interpretation":"srgb"}
After:
{"width":561,"height":504,"bands":4,"format":"uchar","interpretation":"srgb"}

Before:
{"width":800,"height":600,"bands":4,"format":"uchar","interpretation":"srgb"}
After:
{"width":800,"height":504,"bands":4,"format":"uchar","interpretation":"srgb"}
```

Expected output:
```
Before:
{"width":800,"height":600,"bands":4,"format":"uchar","interpretation":"srgb"}
After:
{"width":561,"height":504,"bands":4,"format":"uchar","interpretation":"srgb"}

Before:
{"width":800,"height":600,"bands":4,"format":"uchar","interpretation":"srgb"}
After:
{"width":561,"height":504,"bands":4,"format":"uchar","interpretation":"srgb"}
```
(Because there is no difference in the image itself, it's only `pngcrush`'d)

**Comment by jcupitt** [comment]
The png has lots of extraneous crap in the background which is then hidden by the transparency, so you need to multiply that out. A simple solution would be to use `.premultiply()`:

http://www.vips.ecs.soton.ac.uk/supported/current/doc/html/libvips/libvips-conversion.html#vips-premultiply

Only use that if the image has an alpha channel. The test vips uses for has-alpha is here:

https://github.com/jcupitt/libvips/blob/master/libvips/iofuncs/image.c#L2778

We should probably add a has-alpha predicate to php-vips.

A faster alternative for trimming images with an alpha channel would be to just test the final channel for non-zero. It's obviously fine to trim away all transparent parts.

**Comment by kleisauke** [comment]
`->premultiply()` fixes this, thanks!

I agree a `->hasAlpha()` function will come in handy. We could add something like this:

```php
/**
 * Does this image have an alpha channel?
 * Uses colour space interpretation with number of channels to guess this.
 *
 * @param  Image $image The source image.
 *
 * @return bool indicating if this image has an alpha channel.
 */
public function hasAlpha(): bool
{
    $bands = $this->get('bands');
    $interpretation = $this->get('interpretation');

    return $bands === 2 || ($bands === 4 && $interpretation !== Interpretation::CMYK) || $bands > 4;
}
```

(or if 8.5 is released just call `vips_image_hasalpha`)

Not sure what you did mean by 'test the final channel for non-zero'. I tried to separate alpha channel first:
```php
 // If the image has alpha
if($hasAlpha) {
    // Separate alpha channel
    $alphaChannel = $image->extract_band($image->bands - 1, ['n' => 1]);
    $image = $image->extract_band(0, ['n' => $image->bands - 1]);
}
```

And then re-add it before the crop:
```php
if($hasAlpha) {
    $image = $image->bandjoin($alphaChannel);
}
```

But that doesn't seems to work.

Closing this issue because it's fixed with `->premultiply()`. If there's a faster way (not sure how fast pre-multiplying is), then let me know.

**Comment by jcupitt** [comment]
git master has a hasAlpha method now:

https://github.com/jcupitt/libvips/blob/master/libvips/iofuncs/image.c#L2778

I guess you know, but you can write `$image->get('bands')` as `$image->bands`, which makes it slightly neater.

**Comment by kleisauke** [comment]
Thanks! Indeed, the magic get method is neater. Not sure why I didn't use that in the `toString` method, thanks for correcting that. 👍
