### ISSUE TITLE
vips_foreign_find_load missing

### ISSUE THREAD

**Issue by kleisauke** [jcupitt/php-vips#37]
In order to pass the correct options before the `Image::newFromFile` operation, the `vips_foreign_find_load` will come in handy to determine the image format.

Example:
The page property works only for PDFs, TIFFs, and multi-size ICOs (or any other image that has more than one page). But doesn't work for a JPEG (it will fail with the error: `Message: jpegload: no property named 'page'`). In order to pass the page property to the correct loader we can check first with `vips_foreign_find_load` if the operation permits a page property.

**Comment by jcupitt** [comment]
I agree, I think it'd be a useful improvement. We should add the one for buffers as well, I guess. 

In the meantime, you could just open the file and look at the `vips-loader` property. It records the name of the load operation that was used:

```
$ vipsheader -f vips-loader k2.jpg 
jpegload
```

So open once, get loader name, open a second time with whatever arguments you want.

**Comment by jcupitt** [comment]
OK, in git master. Thanks!

**Comment by jcupitt** [comment]
git master php-vips has a wrapper as well, with a fallback to the property method:

https://github.com/jcupitt/php-vips/blob/master/src/Image.php#L716

and a version for buffers.

**Comment by kleisauke** [comment]
Nice! Travis is currently failing because the newest version of php-vips-ext isn't on PECL yet, I think we can ignore it for now.

**Comment by jcupitt** [comment]
OK, fixed travis. It turns out you can't `catch` undefined functions :(
