### ISSUE TITLE
Exception: "f1.jpg" is not a known file format in Image.php:635

### ISSUE THREAD

**Issue by mfenz** [jcupitt/php-vips#39]
Hi! I tried to run the example from the main page of the project, built vips myself, now I run vips-8.4.5. 
But when I try to execute the first example  like ./console.php f1.jpg x.tif I get the following error message: 

PHP Fatal error:  Uncaught Jcupitt\Vips\Exception: VipsForeignLoad: "f1.jpg" is not a known file format
 in /home/x/www/vendor/jcupitt/vips/src/Image.php:635
Stack trace:
#0 /home/x/www/vendor/jcupitt/vips/src/Image.php(656): Jcupitt\Vips\Image::errorVips()
#1 /home/x/www/vendor/jcupitt/vips/src/Image.php(674): Jcupitt\Vips\Image::errorIsArray(-1)
#2 /home/x/www/console.php(6): Jcupitt\Vips\Image::newFromFile('f1.jpg')
#3 {main}
  thrown in /home/x/www/vendor/jcupitt/vips/src/Image.php on line 635

which is line $image = Vips\Image::newFromFile($argv[1]);  in console.php

I tried with several jpg's and png's. 

Unfortunately I don't know where to start to solve the problem.
Thanks very much!

**Comment by jcupitt** [comment]
Hi @mfenz, I would guess your libvips is missing jpeg support. Try running `configure` again and check the table it prints at the end carefully. You should see:

```
file import/export with libjpeg:	yes
image pyramid export:			yes
  (requires libgsf-1 1.14.26 or later)
use libexif to load/save JPEG metadata: yes
```

If you have any "no"s, add some more packages, like `libjpeg-dev`. What platform are you using?

**Comment by mfenz** [comment]
Hi @jcupitt - thank you so much for your fast reply!
That was the problem, in my case 

```
image pyramid export:			no
  (requires libgsf-1 1.14.26 or later)
```

I'm using Debian 8 - packet manager gave me vips 7.x so I built it...
Thanks again, best regards!
