### ISSUE TITLE
How to use the picture as a watermark？

### ISSUE THREAD

**Issue by nick-william** [jcupitt/php-vips#40]
Hi~  how can i do to add a watermark with the picture which is a transparent png

**Comment by jcupitt** [comment]
Hi @nick-william, there's no built-in watermark function, you have to make your own. I made you a demo one, use it like this:

```
$ ./watermark.php ~/pics/owl.jpg x.jpg ~/pics/vips-128a.png
```

To make:

![x](https://cloud.githubusercontent.com/assets/580843/24744508/30f3827e-1aaa-11e7-9772-e803563f0504.jpg)

Obviously you'll want a less ugly watermark image. It should handle mono and colour watermarks, with mono and colour images, with or without alpha, in 8 or 16 bits. 

It won't work well for CMYK images, you'd need to think about how to handle them. Perhaps you don't need CMYK support?

```php
#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use Jcupitt\Vips;

if(count($argv) != 4) {
    echo("usage: ./watermark.php input-image output-image watermark-image\n");
    exit(1);
}

// we can stream the main image
$image = Vips\Image::newFromFile($argv[1], ['access' => 'sequential']);

$output_filename = $argv[2];

// we'll read the watermark image many times, so we need random access for this
$watermark = Vips\Image::newFromFile($argv[3]);

// replicate the watermark image to make something big enough to cover the whole
// of image, then trim down to the exact size we need
$watermark = $watermark->replicate( 
    1 + $image->width / $watermark->width,
    1 + $image->height / $watermark->height);
$watermark = $watermark->crop(0, 0, $image->width, $image->height);

// the watermark image needs to have an alpha channel ... take it off and leave
// just the colour bits ... we support mono and RGB watermarks
if($watermark->bands != 4 && $watermark->bands != 2) {
    echo("watermark image does not have an alpha channel\n");
    exit(1);
}
$watermark_alpha = $watermark->extract_band($watermark->bands - 1);
$watermark = $watermark->extract_band(0, ['n' => $watermark->bands - 1]);

// the main image can have an optional alpha ... we need to remove this before
// we blend the watermark in, we don't want to change the main image alpha
if($image->bands == 2 || $image->bands == 4) {
    $image_alpha = $image->extract_band($image->bands - 1); 
    $image = $image->extract_band(0, ['n' => $image->bands - 1]);
}
else {
    $image_alpha = NULL;
}

// make the watermark match the colourspace of the main image ... this will do
// things like transforming an 8-bit alpha to match a 16-bit image
$watermark = $watermark->colourspace($image->interpretation);

// blend the colour parts of the watermark into the colour parts of the image
// using the watermark alpha .. the blend option means "do a smooth blend"
$image = $watermark_alpha->ifthenelse($watermark, $image, ['blend' => true]);
   
// reattach the image alpha, if any
if($image_alpha) {
    $image = $image->bandjoin($image_alpha);
}

$image->writeToFile($output_filename);
```

**Comment by nick-william** [comment]
Yes~~ it's clear 

 Thank you very much for adding this demo

**Comment by Nicksxs** [comment]
@jcupitt how can i do if i want to customize the watermark location on the image, recently i read the source code of function `vips_ifthenelse`,but did not see any option allow me to set the location, thanks!

**Comment by jcupitt** [comment]
Hi, could you explain what you mean by setting the location? Do you want to change the grid offset?

You could put the offset in the crop, then make sure the image is large enough. For example:

```php
$watermark = $watermark->replicate( 
    2 + $image->width / $watermark->width,
    2 + $image->height / $watermark->height);
$watermark = $watermark->crop($left_offset, $top_offset, $image->width, $image->height);
```

Where `$left_offset` and `$top_offset` say how to offset the grid, and should be less than the size of the watermark.

**Comment by Nicksxs** [comment]
@jcupitt Hi, i use embed function and solve the problem, 
Use the embed function to fill the watermark image as large as the origin image, through this method can set watermark location, like this
```
$watermark = $watermark->embed($image->width - $watermark->width, $image->height - $watermark->height, $image->width, $image->height, ["extend" => 'background', "background" => [0, 0, 0, 0]]);
```
i want to set the watermark on the right bottom conner of the origin image(water mark is much smaller than the origin image), thanks for help, forgive my poor english !

**Comment by nick-william** [comment]
hi~~~  @jcupitt 
I tried to use the above demo write the watermarked image to the original image, but some wrong:
```
...
$image->writeToFile($argv[1]);
...


Fatal error: Uncaught Jcupitt\Vips\Exception: VipsJpeg: Empty input file
VipsRegion: valid clipped to nothing
VipsRegion: valid clipped to nothing
VipsRegion: valid clipped to nothing
 in /Users/william/strong/Test/vendor/jcupitt/vips/src/Image.php:635
Stack trace:
#0 /Users/william/strong/Test/vendor/jcupitt/vips/src/Image.php(738): Jcupitt\Vips\Image::errorVips()
#1 /Users/william/strong/Test/image/demo5.php(60): Jcupitt\Vips\Image->writeToFile('./1.jpeg')
#2 {main}
  thrown in /Users/william/strong/Test/vendor/jcupitt/vips/src/Image.php on line 635

```

**Comment by jcupitt** [comment]
Hi, you can't read from and write to the same file, could that be the problem? You must always write a new file each time. 

The reason is that libvips streams images, so it loads 128x128 pixels from the input image, processes them, then writes 128x128 to the output image, then loads the next 128x128 tile, and so on. If you write to the same file you load from, writing the first tile will destroy the whole of the input image.

**Comment by nick-william** [comment]
ok, got it
If can't read from and write to the same file may be a little problem to me,  but  I can handle it.
Thank you~

**Comment by jcupitt** [comment]
Could you open a new issue, please? It's best to have one question per issue, so other people can find answers easily.
