### ISSUE TITLE
Class not found

### ISSUE THREAD

**Issue by velpaxl** [jcupitt/php-vips#41]
Hello,

I installed the libvips-dev library (on Ubuntu 16.04), so I have the 8.2.2 version, then I installed the vips-php-ext with pecl, I added the extension to the php.ini and I added the composer info and updated it.
I'm trying to use the Vips Library in a Symfony 3 project, but each time I called on a function, like reduce I get this error : `VipsOperation: class "reduce" not found`

I don't know whom to ask or where so that's why I'm posting it here.

Thanks for any advice.

**Comment by jcupitt** [comment]
Hello, the `reduce` operations were added in 8.3, so you'll need to update your libvips. The current stable version is 8.5:

https://jcupitt.github.io/libvips/
https://github.com/jcupitt/libvips/releases

There are some notes on how to compile your own vips here:

https://jcupitt.github.io/libvips/install.html#building-libvips-from-a-source-tarball

Are you making image thumbnails? 8.5 has a new operator called `thumbnail` which does everything in a single step. There are some notes here:

https://jcupitt.github.io/libvips/2017/03/16/What's-new-in-8.5.html

Or the API docs are here:

https://jcupitt.github.io/libvips/API/current/libvips-resample.html#vips-thumbnail

**Comment by velpaxl** [comment]
Thank you so much.

I had to do a `sudo pecl uninstall vips` and then again `sudo pecl install vips` in order to make it work, after compiling the 8.5 version of the library.
Effectively, I wanted to test out the thumbnail function and it works like a charm.

Once again, thanks for your help and your quickness in responding to me.

**Comment by jarodium** [comment]
Hello
When does 8.5 lands on the repos so I can upgrade from apt ?

**Comment by jcupitt** [comment]
Hi, Ubuntu should update in October.

**Comment by jdongelmans** [comment]
Any updates on this? October has past and I would really like the ```thumbnail``` operation in the version from the apt repo :)

**Comment by jcupitt** [comment]
I just checked and it seems Ubuntu updated to 8.4.5, but not 8.5 :( It seems the Debian package hasn't been touched for a while. 8.6 is due soon, I'll try to nudge the maintainer.

Until then, sorry, you'll have to make your own.
