### ISSUE TITLE
 undefined function Jcupitt\Vips\vips_cache_set_max()

### ISSUE THREAD

**Issue by windshadowlam** [jcupitt/php-vips#43]
Fatal error: Uncaught Error: Call to undefined function Jcupitt\Vips\vips_cache_set_max() in /var/www/cdn.cosmatch.org/imagesweserv/imagesweserv/vendor/jcupitt/vips/src/Config.php:99 Stack trace: #0 /var/www/cdn.cosmatch.org/imagesweserv/imagesweserv/src/Api/Api.php(169): Jcupitt\Vips\Config::cacheSetMax(0) #1 

Ubuntu 16.04 LTS (GNU/Linux 2.6.32-042stab113.21 x86_64)
PHP 7.0.18-0ubuntu0.16.04.1 (cli) ( NTS )

**Comment by jcupitt** [comment]
Hello, git master php-vips uses a couple of functions from the git master of php-vips-ext, the binary extension, which have not been released via pecl.

You need to either install the binary extension by hand, or specify an earlier version of php-vips in your composer file. 

I'll have a look at updating pecl.

**Comment by kleisauke** [comment]
It looks like you're trying to install https://github.com/andrieslouw/imagesweserv. 

To install this project successfully, you'll need [`php-vips-ext`](https://github.com/jcupitt/php-vips-ext) >= 1.0.7 (which can be found on [PECL](https://pecl.php.net/package/vips)). I've just updated our main branch to check if the required PHP extension has been installed (when you run `composer install`).

**Comment by windshadowlam** [comment]
yes,thank you.

**Comment by windshadowlam** [comment]
Sorry, but still getting the error after git pull and composer install

**Comment by kleisauke** [comment]
@windshadowlam Did you install the binary PHP extension?
```
pecl install vips
```

Maybe a reload of the config file is needed (if you're using NGINX and PHP-FPM):
```bash
 sudo service php7.0-fpm reload
```

**Comment by windshadowlam** [comment]
root@:~# pecl install vips
pecl/vips is already installed and is the same as the released version 1.0.7
install failed
and i also restarted:
root@:~# service apache2 restart

**Comment by jcupitt** [comment]
I see:

```
$ php -r 'echo phpversion("vips") . "\n";'
1.0.7
```

Assuming you've enabled vips for the php cli. Or try on a webpage if you're just using apache. 

Did you add `extension=vips.so` to your `php.ini`? On Ubuntu it's best to make a file called `vips.ini` in `mods-available` and then link to that from `conf.d`.

**Comment by windshadowlam** [comment]
after linking, i got
Error 410: Server couldn't parse the ?url= that you were looking for, because the hostname of the origin is unresolvable (DNS) or blocked by policy.

is it Done? Where should I set the policy?

**Comment by kleisauke** [comment]
I think this issue can be closed now. If you have any further questions or problems installing imagesweserv, feel free to create an issue at https://github.com/andrieslouw/imagesweserv.
