### ISSUE TITLE
dzsave_buffer Question

### ISSUE THREAD

**Issue by bubba-h57** [jcupitt/php-vips#44]
`* @method string dzsave_buffer(array $options = []) Save image to dz buffer.`

This intrigues me! I simply do not know what to do with it tho.

`$blob = $image->dzsave_buffer(['layout' => 'zoomify']) `

Can I do that? If I do, what really ends up in the blob? All the individual tiles? 

It would be downright epic and awesome if I could do something such as:

```php
$this->tarStream = new TarStreamer(
  | ['outstream' => fopen('s3://my-bucket/zoomify.tar', 'w')]
  | );

$this->tarStream->fromBuffer($image->dzsave_buffer(['layout' => 'zoomify']) );
```

Ofcourse [TarStreamer](https://github.com/barracudanetworks/ArchiveStream-php) does not have a `fromBuffer()` method, so I would need to figure out how to read directories and files from the `dzsave_buffer` and add them to the TarStream if possible.

**Comment by jcupitt** [comment]
That's right, though it builds a zip rather than a tar. Just write that string to a file and you should be able to unzip it.

**Comment by bubba-h57** [comment]
Does it stream the output? Or does it simply pass back one big blob?

**Comment by jcupitt** [comment]
Just a big blob at the end. But that's a problem with zip, it's not really a streamable container format.

**Comment by bubba-h57** [comment]
Oh yes, that is right Zips and PDFs pft. Thanks!

**Comment by bubba-h57** [comment]
This works:
`$image->dzsave('/tmp/zoomified.zip', ['layout' => 'zoomify', 'container' => 'zip']);`
and I get a nice zipfile.

`$sourceBlob = $image->dzsave_buffer(['layout' => 'zoomify', 'container' => 'zip']);`

This, however, fails with the following exception:

```
2017-07-06T16:58:28+0000  priority=INFO, channel="filecabinet-lambda", httpHost="CLI", transactionID="595e6c316c814", message="VipsOperation: class "dzsave_buffer" not found
"
2017-07-06T16:58:28+0000  priority=INFO, channel="filecabinet-lambda", httpHost="CLI", transactionID="595e6c316c814", message="#0 /Users/bubba/dev/stechstudio/FileCabinet-Lambda/project/vendor/jcupitt/vips/src/Image.php(685): Jcupitt\Vips\Image::errorVips()
#1 /Users/bubba/dev/stechstudio/FileCabinet-Lambda/project/vendor/jcupitt/vips/src/Image.php(1052): Jcupitt\Vips\Image::errorIsArray(-1)
#2 /Users/bubba/dev/stechstudio/FileCabinet-Lambda/project/vendor/jcupitt/vips/src/Image.php(1130): Jcupitt\Vips\Image::callBase('dzsave_buffer', Object(Jcupitt\Vips\Image), Array)
#3 /Users/bubba/dev/stechstudio/FileCabinet-Lambda/project/app/Pipeline/Pipes/ConvertImage.php(57): Jcupitt\Vips\Image->__call('dzsave_buffer', Array)
#4 /Users/bubba/dev/stechstudio/FileCabinet-Lambda/project/app/Pipeline/Pipes/ConvertImage.php(18): App\Pipeline\Pipes\ConvertImage->zoomifySource(Object(App\Models\SnsEvent))
```

I am not sure if I am doing it wrong, or if it is a legitimate bug. *VipsOperation: class "dzsave_buffer" not found* appears to indicate that it is missing from the extension? Should I open a separate bug report if it is a bug?

**Comment by jcupitt** [comment]
Which libvips are you using? It's a fairly new feature.

**Comment by bubba-h57** [comment]
> ╰─ brew info vips
> vips: stable 8.5.6 (bottled)
> Image processing library
> https://github.com/jcupitt/libvips
> /usr/local/Cellar/vips/8.4.5 (175 files, 12.5MB) *
>   Poured from bottle on 2017-04-04 at 10:36:20
> From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/vips.rb

Well pft ... I suppose I just assumed my brew was up to date. That was definitely the issue.
