### ISSUE TITLE
Question: Get information of a certain pixel

### ISSUE THREAD

**Issue by olivervogel** [jcupitt/php-vips#45]
I'm currently struggeling to figure out, how to get color information of a certain pixel at a given position of an image. Something like [imagecolorat()](http://php.net/manual/en/function.imagecolorat.php) for GD does.

I guess I have to use the histogram functions. But I'm not sure.

Any help or tip would be appreciated.

**Comment by jcupitt** [comment]
Hello @olivervogel, you can use `getpoint`:

http://jcupitt.github.io/libvips/API/current/libvips-arithmetic.html#vips-getpoint

For example:

```php
$image = Vips\Image::newFromFile("k2.jpg");
$pixel = $image->getpoint(0, 0);
echo "pixel = ";
print_r($pixel);
```

Prints:

```pixel = Array
(
    [0] => 11
    [1] => 1
    [2] => 0
)
```

**Comment by olivervogel** [comment]
Thank your @jcupitt. Didn't found this method in the PHP-VIPS docs.

**Comment by jcupitt** [comment]
I agree, it seems to have fallen off the docs. I'll look into it.

**Comment by jcupitt** [comment]
I found a problem in the way the docs were being generated. It seems phpdoc does not understand type specifications on array returns. I've changed the docs to just return plain array for all compound results and getpoint has appeared:

https://jcupitt.github.io/php-vips/docs/classes/Jcupitt.Vips.ImageAutodoc.html#method_getpoint

Thanks for pointing this out!
