### ISSUE TITLE
vips_text color text?

### ISSUE THREAD

**Issue by dubcanada** [jcupitt/php-vips#46]
Hello,

I am using something like

        $big = Vips\Image::newFromFile("file.jpg");

        $text = Vips\Image::text("HELLO, [
            'font' => 'sans 120'
        ]);

        // Embed text in larger image
        $text = $text->embed($x, $y, $big->width, $big->height);

        // Set the text alpha
        $text_alpha = $text->extract_band($text->bands - 1);
        $text = $text->extract_band(0, ['n' => $text->bands - 1]);

        // Blend the text and the image
        $out = $text_alpha->ifthenelse($text, $big, ['blend' => true]);

And that seems to be working well, I can blend text into the image with no background. My problem is I am trying to change the color of the text from white to say red, but I have no idea how to do that. I can't seem to find anything in the documentation on how to colorize the text.

Any suggestions?

**Comment by jcupitt** [comment]
Hello, there's no text alpha, it's a one-band image of 0 - 255 values. It IS the alpha. You need to use the text mask to blend between your image and a solid colour. 

For example:

```php
    $big = Vips\Image::newFromFile("file.jpg");

    $text = Vips\Image::text("HELLO, [
        'font' => 'sans 120'
    ]);

    // Embed text in larger image
    $text = $text->embed($x, $y, $big->width, $big->height);

    // Blend the text and the colour red
    $out = $text->ifthenelse([255, 0, 0], $big, ['blend' => true]);
```

You can blend between two images if you want textured text, for example, or scale the text down if you want to make it transparent.

**Comment by YasirAlawa** [comment]
You can use something like that
`vips_text(out,"<span foreground=\"red\">Red!</span>"NULL);`

**Comment by jcupitt** [comment]
Hi again, yes, `text` now supports RGBA output, but you must enable it with the `rgba` flag. For example, in php:

```php
    $text = Vips\Image::text("<span foreground=\"red\">Red!</span>", [
        'font' => 'sans 120'
        'rgba' => true
    ]);
    $text->WriteToFile("x.png");
```

Generates:

![x](https://user-images.githubusercontent.com/580843/131426912-e2f47e0d-e37e-4934-8be9-cae285eb5a09.png)
