### ISSUE TITLE
tiffsave_buffer

### ISSUE THREAD

**Issue by bubba-h57** [jcupitt/php-vips#47]
I can not seem to figure out the `tiffsave_buffer` method. If I simply use `tiffsave` it works as expected, but this is what I get with the buffer.

```php
$tifOptions = [
        'compression' => 'jpeg',
        'tile' => true,
        'pyramid' => true
    ];
$image = Image::newFromFile($pageSource);
$tiffBlob = $image->tiffsave_buffer($tifOptions);
```

> TIFFOpen: (null): Bad address tiff: unable to open "(null)" for input, exception="[object] (Jcupitt\Vips\Exception(code: 0): TIFFOpen: (null): Bad address tiff: unable to open "(null)" for input at /vendor/jcupitt/vips/src/Image.php:664)
> 
> [stacktrace]
> #0 /vendor/jcupitt/vips/src/Image.php(685): Jcupitt\Vips\Image::errorVips()
> #1 /vendor/jcupitt/vips/src/Image.php(1052): Jcupitt\Vips\Image::errorIsArray(-1)
> #2 /vendor/jcupitt/vips/src/Image.php(1130): Jcupitt\Vips\Image::callBase('tiffsave_buffer', Object(Jcupitt\Vips\Image), Array)

Am I doing it wrong?

**Comment by jcupitt** [comment]
Hello, there's an example here:

https://github.com/jcupitt/php-vips/blob/master/tests/write.php#L47

That's for `.jpg`, but just use `.tif` instead and it should work. 

`tiffsave_buffer` was added in 8.5, so make sure you have at least 8.5.0.

**Comment by bubba-h57** [comment]
So, changing my code to

```
$tifOptions = [
        'compression' => 'jpeg',
        'tile' => true,
        'pyramid' => true
    ];
$image = Image::newFromFile($pageSource);
try {
    $tiffBlob = $image->writeToBuffer('.tif', $this->tifOptions);
} catch (\Exception $e) {
    dd($e);
} 
```

gives me precisely the same error. I am running:

> ╰─ vips --version
>      vips-8.5.6-Sat Jul 22 10:12:12 BST 2017
> 
> ╰─ php -i | grep vips
>      vips
>      vips property => value
>      VIPSHOME => /usr/local/Cellar/vips/8.5.6_2
>      $_SERVER['VIPSHOME'] => /usr/local/Cellar/vips/8.5.6_2

**Comment by bubba-h57** [comment]
It appears to be the `'pyramid' => true` flag. If I do not use that option, everything works as expected ... but as soon as I try for a pyramid tiff, it goes toes up.

**Comment by jcupitt** [comment]
Ooop, sorry, I hadn't noticed the pyramid flag there. You're right, tiffsave_buffer does not support pyramid images. I guess this is a bug, sorry. I'll see if there's an easy fix.

**Comment by jcupitt** [comment]
OK, added a bug on the main libvips tracker. Thanks for pointing this out.

**Comment by jcupitt** [comment]
Done and working, it'll be in 8.6.
