### ISSUE TITLE
add exceptions

### ISSUE THREAD

**Issue by jcupitt** [jcupitt/php-vips#5]
Maybe add exceptions, are they commonly used in PHP? Unclear.

**Comment by jcupitt** [comment]
Almost there. TODO:

- [ ] we need to do something about errors from `__get()`
- [ ] it's just `Exception` at the moment, we should maybe have a `Vips\Exception`

**Comment by kleisauke** [comment]
+1 on `Vips\Exception`,  now it's hard to catch an libvips exception.

Useful link: http://stackoverflow.com/a/6621608/1480019

**Comment by jcupitt** [comment]
OK, `Vips\exception` is in, I think: https://github.com/jcupitt/php-vips/commit/ac84e4bce8bcdd781dc120a73a0566a5c807a565

Does that look OK?

**Comment by kleisauke** [comment]
@jcupitt Apart from 2 small comments, I think this looks OK. Thanks for adding this.

**Comment by jcupitt** [comment]
OK, comments addressed with https://github.com/jcupitt/php-vips/commit/497812b7688b71570d997b2ecc224381f3b76965
