### ISSUE TITLE
How to create an empty image with a background color

### ISSUE THREAD

**Issue by chregu** [jcupitt/php-vips#57]
I'm trying to write a vips integration for the php imagine library, one point I struggle currently is, how to generate an "empty" image with a certain width and height and a background color. I didn't find an easy way with googling. Any suggestions? 
It's basically the create method here https://github.com/liip-forks/Imagine/blob/vips/lib/Imagine/Vips/Imagine.php#L60 but instead of using imagick, it should of course use vips.

Any hints are very much appreciated

**Comment by jcupitt** [comment]
Hello Christian,

There are a couple of ways. The simplest is `newFromImage`:

https://jcupitt.github.io/php-vips/docs/classes/Jcupitt.Vips.Image.html#method_newFromImage

If you have an existing image, it makes some like that, but with a constant value for each pixel.

You can see how it works here:

https://github.com/jcupitt/php-vips/blob/master/src/Image.php#L972

```php

        $pixel = self::black(1, 1)->add($value)->cast($this->format);
        $image = $pixel->embed(
            0,
            0,
            $this->width,
            $this->height,
            ['extend' => Extend::COPY]
        );
```

ie. you make a 1x1 pixel black image, then add the constant value you want (this can be an array for a multi-band image), cast to the type you want (uchar, ushort, whatever), then use `embed` to expand it to the full size you need.

**Comment by kleisauke** [comment]
In addition to John's answer, I've made a simple script to create an image with a certain width, height and background color:
https://gist.github.com/kleisauke/a8cdd74c63738eb3add7d9422458aed8

To create a red image (100x100) with 50% alpha:
![50-percent-red](https://user-images.githubusercontent.com/12746591/32901903-52cb6e8c-caf1-11e7-85a0-e0992dc9332a.png)

```php
$image = create(100, 100, '#80FF0000');
$image->writeToFile('50-percent-red.png');
```

The color (third parameter) needs hexadecimal RGB or ARGB values, which can be formatted as:
- 3 digit RGB: `RGB`
- 4 digit ARGB (alpha): `ARGB` 
- 6 digit RGB: `RRGGBB`
- 8 digit ARGB (alpha): `AARRGGBB`

That first pair of letters, the AA, represent the alpha channel. You must convert your decimal opacity values to a hexadecimal value. [Here's a table](https://jsfiddle.net/owc8m6xh/embedded/result/) of percentages to hexadecimal values (from 100% to 0% alpha). For example, 50% white you'd use `80FFFFFF`.

**Comment by chregu** [comment]
Thanks a lot to both of you, that worked, it's implemented here
 here https://github.com/liip-forks/Imagine/blob/vips/lib/Imagine/Vips/Imagine.php#L63
