### ISSUE TITLE
affine should have a background parameter, and not have jaggy edges

### ISSUE THREAD

**Issue by chregu** [jcupitt/php-vips#58]
I try to rotate an image by arbitrary angle. Basically works fine with just `similarity`, but the borders look pretty jagged, compared to what for example imagick produces.

Any hints to make them smoother?
With VIPS:
![vips](https://user-images.githubusercontent.com/47106/32914931-87085d4c-cb17-11e7-9188-1be57701feb6.png)
With IMagick:
![imagick](https://user-images.githubusercontent.com/47106/32914932-8723eeea-cb17-11e7-9f78-0acdf6f009d7.png)

I'd also like to have a user-definable "background" layer instead of just an fully transparent alpha channel. For now I do this with:

```
                        $aa = $this->vips->extract_band(3);
                        $this->vips = $aa->ifthenelse($this->vips, $background);
```

But I assume this doesn't really work nicely, in case I happen to have smooth borders with hopefully also smoothness on the alpha channel for the rotated image. How would I put the rotated image on top of the background image (which can have an alpha channel as well)? Basically a `compositeImage` operation in IMagick, I assume.

**Comment by jcupitt** [comment]
I agree, the jagged edges are ugly, they should be fixed.

In the meantime, you can add a one-pixel border around the input image, the same colour as the background for similarity (ie. always black). You're right, a parameter to set the background for `affine` and `similarity` would be useful.

You can use `flatten` to composite an image with transparency against a background colour, would that help? It's the thing `jpegsave` uses to implement the `background` parameter there.

8.6 has a new `composite` operator that can merge a stack of transparent images using a set of PDF blend modes (so over, multiply, saturate etc.), which I think would be useful for you. 8.6 is sadly still not out, perhaps another week or two.

**Comment by jcupitt** [comment]
I've made this into an enhancement issue for `affine`, I hope that's OK.

**Comment by chregu** [comment]
Thanks for the answer, looking forward to the enhancements. 

Was also thinking about adding a border before rotating. What's the best way to do this? (I hope my questions aren't too basic, but I couldn't figure that one out)

I assume flatten doesn't help in this case, since the background can have transparency as well, which I'd like to keep. But hopefully composite will solve my problems.

**Comment by jcupitt** [comment]
Use `embed` to add borders:

https://jcupitt.github.io/php-vips/docs/classes/Jcupitt.Vips.ImageAutodoc.html#method_embed

The C docs have more detail:

https://jcupitt.github.io/libvips/API/current/libvips-conversion.html#vips-embed

However, I think the right place to fix this would be in libvips. Let me see if I can address this in 8.6, and then you can avoid adding ugly workarounds to your code.

**Comment by jcupitt** [comment]
There's an issue on the main libvips repo to track this improvement.

**Comment by jcupitt** [comment]
It seems to be fixed in this branch:

https://github.com/jcupitt/libvips/tree/fix-affine-jaggies

With this command:

```
$ vips similarity grid.png x.png --angle 30 --background 128
```

I see:

![x](https://user-images.githubusercontent.com/580843/32957974-09f64956-cbb5-11e7-9f46-1c60a91476d0.png)

Would you be able to test this?

**Comment by chregu** [comment]
Thanks for the quick fix. Looks good in general, only when I use eg. black  color with full transparency ([0,0,0,255] in PHP), it looks kinda wrong
![29ccea](https://user-images.githubusercontent.com/47106/32961226-fe260cd4-cbc7-11e7-967f-7f3ab0fd5ab0.png)

But way better than before

**Comment by chregu** [comment]
btw, can confirm that the composite works, eg:
```
        $image = $image->composite([$image, $insertImage], [2]);
```
works nicely, also with alpha channels. Looking forward to see #55 implemented to have consts for those ints.

**Comment by jcupitt** [comment]
It wasn't premultiplying alpha, which can add edges on resampling. Could you test again?

Funny how fiddly it can be to get all the edge cases out.

**Comment by jcupitt** [comment]
Oh, test image:

![grid-rgba](https://user-images.githubusercontent.com/580843/32979713-6b678310-cc52-11e7-9d7c-c54c99d0d521.png)

Command:

```
$ vips similarity grid-rgba.png x.png --angle 30
```

Result:

![x](https://user-images.githubusercontent.com/580843/32979714-817da904-cc52-11e7-8460-ceae831cf088.png)

**Comment by chregu** [comment]
The borders are fine now, but the background (apart from the direct border pixels) is now always totally transparent, with for example ['background' => [0,0,0,255]]. On purpose, so I should composite a background in?

**Comment by jcupitt** [comment]
Groan, what an idiot, I forgot to convert the background to the pixel format of the premultiplied image. Try again, I now see:

```
$ vips similarity grid-rgba.png x.png --angle 30 --background "128 0 0 255"
```

![x](https://user-images.githubusercontent.com/580843/32980889-88f42f64-cc66-11e7-8afb-3fdeedb5c6ce.png)

**Comment by chregu** [comment]
perfect. thanks a lot, looking forward to 8.6

**Comment by jcupitt** [comment]
Thank you very much for testing this. I'll merge to master and add stuff for this to the test suite.
