### ISSUE TITLE
add logging

### ISSUE THREAD

**Issue by jcupitt** [jcupitt/php-vips#6]
Add support for `vips_info()`, tracing, progress, debug and logging. Perhaps things like vips cache control too.

**Comment by jcupitt** [comment]
Almost there. TODO:

- [ ] we need to do something about errors from `__get()`
- [ ] it's just `Exception` at the moment, we should maybe have a `Vips\Exception`

**Comment by kleisauke** [comment]
@jcupitt It's now hard to log only specific things (like errors or specific operations) and we're now not able to log to a file. 

My idea is to allow the user to define his own logger class where he can use his own logic to log operations, errors and operations results. I've made a simple example to clarify some things: https://gist.github.com/kleisauke/b4536bdc02e2a83ac8108f7ac9a23a76

**Comment by jcupitt** [comment]
I agree, the logging is about as crude as it could be. The Python one uses the standard logging framework too.

Do whatever you like and make a pull request, I promise to merge!

**Comment by jcupitt** [comment]
Or shall I mark you as a collaborator? Then you can commit directly yourself.

**Comment by kleisauke** [comment]
@jcupitt Pull request has been made: https://github.com/jcupitt/php-vips/pull/15

About collaborator access:
I do like to contribute to this repository to improve my technical skills. I'm not sure how much time I want to spend to contributing, because my priorities are to finish my bachelor degree (I'm studying computer science). If you don't mind about code frequency; than I'm open for collaboration access.
As always, I'm willing to make this repository better.

**Comment by jcupitt** [comment]
OK, I've sent a collaborator invite.

It's no problem with just occasional commits. This is a spare-time project for me too, so I think I understand.

We should probably have a short document somewhere setting the scope and roadmap for this repository. I suggest:

* php-vips is a binding for libvips, in line with ruby-vips, pyvips, the libvips C++ API and the libvips C API.
* It aims to be small and simple, and to provide a stable, well-documented platform that conforms to standard php best practice.  
* Extra functionality, such as an image thumbnailer, for example, should be implemented in repositories which build on this one, and not incorporated directly in this code. 
* As much of the binding as possible is auto-generated. This reduces maintenance effort, increases reliability, and makes it possible to reuse core libvips documentation.

What do you think? Hopefully once this thing hits 1.0 it'll barely need touching again. 

I suppose things like Windows support would need significant extra effort. I tried on a Mac yesterday and had some problems, so there's a bit of work there too.

**Comment by kleisauke** [comment]
Thanks for the collaborator invite! I agree that we should somewhere document your nicely written scope/roadmap.

Windows and Mac support would be nice. I think the most extra effort is making `php-vips-ext` compatible for Windows.

Question about my contributing function:
I assume that I should commit breaking changes in a other branch (named my change) and make a pull request to the relevant branch for reviewing process. For non-breaking changes I'm not sure. For example, I can commit it directly into the dev-branch.  What do you prefer? And is there a branching strategy?

**Comment by jcupitt** [comment]
I'll add some text to the README then, if you agree to those bullet points. 

Branching strategy: it seems master should be current stable for composer, so we should use dev for current development. It should always pass the unit tests, and we should check that (and master I guess) with travis.

Beyond that, I'm not sure we need to formalize it. For small things, just commit to dev as you please. If it's something big you think needs review, then open a PR. I'll do the same.

**Comment by kleisauke** [comment]
I agree to those bullet points.

Some formatting (links etc.):
- php-vips is a binding for [libvips](https://github.com/jcupitt/libvips), in line with [ruby-vips](https://github.com/jcupitt/ruby-vips), [pyvips](https://github.com/jcupitt/libvips/tree/master/python), the [libvips C++ API](https://github.com/jcupitt/libvips/tree/master/cplusplus) and the [libvips C API](https://github.com/jcupitt/libvips/tree/master/libvips).
- It aims to be small and simple, and to provide a stable, well-documented platform that conforms to [PHP standards recommendations](http://www.php-fig.org/psr/).
- Extra functionality, such as an image thumbnailer, for example, should be implemented in repositories which build on this one, and not incorporated directly in this code.
- As much of the binding as possible is auto-generated. This reduces maintenance effort, increases reliability, and makes it possible to reuse core libvips documentation.

About the extra functionality (bullet point 3):
I agree that we should not incorporate the `image thumbnailer` (for example) into the `Image` class.
However we could expand the `examples` directory for common image adjustments. (trimming, masking, etc.).
I made a beginning with expanding the examples (a trimming image example): https://gist.github.com/kleisauke/aa8498f11dc2f4c0e2a2362be95473ef
