### ISSUE TITLE
Upscaling without premultiply and alpha channel produces black border

### ISSUE THREAD

**Issue by chregu** [jcupitt/php-vips#61]
When I do the following (upscaling an image from 300 to 400 px), i get a thin black border on top and right. When I add premultiply and unpremultiply, that border is gone. I though that's only needed when the picture has an alpha channel? Wrong assumption? Should I premultiply always? Or just when upscaling? But always when with alpha channel? 

```
$pixel = \Jcupitt\Vips\Image::black(1, 1)->add([255 , 255, 255])->cast(BandFormat::UCHAR);
$vips = $pixel->embed(0, 0, 300, 300, ['extend' => Extend::COPY]);
$vips = $vips->copy(['interpretation' =>\Jcupitt\Vips\Interpretation::SRGB]);

//$vips = $vips->premultiply();
$vips = $vips->resize(400/$vips->width);
//$vips = $vips->unpremultiply();

$vips->jpegsave("image.jpg");

```

**Comment by jcupitt** [comment]
Oh dear, looks like an unforseen consequence of the switch to centre sampling for upscale. I'll see if I can fix it.

**Comment by jcupitt** [comment]
OK, seems to be fixed. Thanks for reporting this! It should be in 8.6 final.

**Comment by chregu** [comment]
Works for me too now, as well, thanks a lot
