### ISSUE TITLE
Question: Count of unique colors

### ISSUE THREAD

**Issue by chregu** [jcupitt/php-vips#65]
Hi

Just a short question: Is there an easy way to get the count of unique colors of a picture?

My use case is, I need a very very rough estimation, if an image could be a photo or not (like a graph, logo, etc). And counting the colors should be good enough for that. Or any other idea, how I could solve this?

**Comment by jcupitt** [comment]
Hello, how about the image entropy?

http://uk.mathworks.com/help/images/ref/entropy.html

In libvips, you can find this with:

```
john@kiwi:~/pics$ vips hist_find k2.jpg x.v
john@kiwi:~/pics$ vips hist_entropy x.v
9.288301
john@kiwi:~/pics$ vips hist_find ISO_12233-reschart.pdf x.v
john@kiwi:~/pics$ vips hist_entropy x.v
3.737180
```

So a photo scores about 10, line art about 4.

In PHP it'd be:

```php
$entropy = $image->hist_find()->hist_entropy();
```

**Comment by chregu** [comment]
Wonderful, that seems to be a good approach. Thanks a lot.
