### ISSUE TITLE
Only resize if smaller/larger

### ISSUE THREAD

**Issue by andrews05** [jcupitt/php-vips#68]
So the documentation for vipsthumbnail mentions
> You can append < or > to mean only resize if the image is smaller or larger than the target.

How do I do this in php?

**Comment by jcupitt** [comment]
Hello @andrews05, the C docs have all the detail:

http://jcupitt.github.io/libvips/API/current/libvips-resample.html#vips-thumbnail

So you use the optional `size` parameter, for example:

```php
$tiny = $huge->thumbnail(128, ["size" => "down"]);
```

And it'll only downsize.

**Comment by andrews05** [comment]
Thank you! Sorry, still finding my way around the documentation I need.
