### ISSUE TITLE
Load images directly from S3 bucket or using a resource

### ISSUE THREAD

**Issue by bensquire** [jcupitt/php-vips#70]
Not sure if this is possible, but could php-vips load data directly from an S3 bucket? Currently we're having to load the image into a string and then pass that into php-vips. For example:

    $buffer = file_get_contents("s3://$bucket/$filename");

    if ($buffer === false) {
        throw new NotFoundException('Unable to open file.');
    }

    $im = \Jcupitt\Vips\Image::newFromBuffer($buffer);
    $rotated = $im->rot('d' . $rotation);
    return $rotated->writeToBuffer('.' . $desiredExtension);

but this involves loading what could potentially be a 15MB file directly into memory before it can be processed. 

Using:

    $im = \Jcupitt\Vips\Image::newFromFile("s3://$bucket/$filename");

results in an error:

> VipsForeignLoad: file "s3://foo/bar.jpg" not found

even though we've registered our S3Connection within a stream wrapper. I also tried to load the image using a resource, e.g:

    $stream = fopen("s3://$bucket/$filename", 'r');

but get the error:

> Argument 1 passed to Jcupitt\Vips\Image::newFromBuffer() must be of the type string, resource given

so that scuppered that idea as well.

Thanks in advance for the help!

**Comment by jcupitt** [comment]
Hello @bensquire,

No, you have to go via a string. This is oe of those features that's been talked about a lot, but has never quite happened, for various reasons. Maybe in the next version.

Some background:

https://github.com/lovell/sharp/issues/30

**Comment by bensquire** [comment]
@jcupitt Thanks for the prompt response and additional information.

I'll hope it does make it into the next version as we're using php-vips to do image manipulation on GET requests, using resources I hope would improve speed/performance etc.

Fingers crossed and thanks for the hard work!

**Comment by jcupitt** [comment]
It probably wouln't make a huge difference since S3 will supply that 15mb in only a few ms. 

Speedup checklist:

* use `thumbnail` for image resizing, not `resize`
* use `access="sequential"` when you can 
* if you are doing pixel arithmetic, keep the format as small as you can by casting results back down
* add cache nodes for results that will be reused a lot

**Comment by bensquire** [comment]
Thanks @jcupitt 

I'm looking to use the thumbnail method as suggested. I can see how I can set width & height, but how can set whether I want it to crop or not? I noticed libvips has smart crop, but that wasn't accepted as an option?

I don't think point 2 and 3 apply to us. But we have point 4 already.

Thanks!
Ben

**Comment by jcupitt** [comment]
Could you explain what kind of cropping you need to do?

**Comment by bensquire** [comment]
So for example, we have an image. It's 1024x768.

We allow users to specify a new image size for thumbs with an optional "fit" flag. So if for example, I specify a new image size of 800x300, the difference between fit and non-fit, would be that one would equally trim the edges, the other would just force the content into the new image size...

Actually as I play with the `thumbnail` method, I see that its main concern is the image width...

**Comment by jcupitt** [comment]
Ah OK. Just set `crop` to `centre` and it should do what you want:

```
$ vips thumbnail babe.jpg x.jpg 800 --height 300 --crop centre
```

In PHP (untested):

```php
$thumb = Vips\Image::thumbnail($buffer, 800, ["height" => 300, "crop" => "centre"]);
```

**Comment by jcupitt** [comment]
... that will crop the top and bottom equally. To force an aspect ratio change, use `"size" => "force"` rather than `crop`.

**Comment by bensquire** [comment]
@jcupitt That is *exactly* what I was looking for, thank-you. How can I derive these sort of options for myself?

**Comment by jcupitt** [comment]
You can use the `vips` command-line tool to get a summary:

```
$ vips thumbnail_buffer
generate thumbnail from buffer
usage:
   thumbnail_buffer buffer out width [--option-name option-value ...]
where:
   buffer       - Buffer to load from, input VipsBlob
   out          - Output image, output VipsImage
   width        - Size to this width, input gint
			default: 1
			min: 1, max: 10000000
optional arguments:
   height       - Size to this height, input gint
			default: 1
			min: 1, max: 10000000
   size         - Only upsize, only downsize, or both, input VipsSize
			default: both
			allowed: both, up, down, force
   auto-rotate  - Use orientation tags to rotate image upright, input gboolean
			default: true
   crop         - Reduce to fill target rectangle, then crop, input VipsInteresting
			default: none
			allowed: none, centre, entropy, attention
   linear       - Reduce in linear light, input gboolean
			default: false
   import-profile - Fallback import profile, input gchararray
   export-profile - Fallback export profile, input gchararray
   intent       - Rendering intent, input VipsIntent
			default: relative
			allowed: perceptual, relative, saturation, absolute
operation flags: nocache 
```

Or the C docs have the details:

http://jcupitt.github.io/libvips/API/current/libvips-resample.html#vips-thumbnail

Obviously that's for C, but it and the PHP interface are just thin layers over the underlying object model, so it should be easy to see how to translate the options into PHP. 

It'd be nice if the PHP docs listed all the options, but sadly php-doc does not seem to allow optional arguments to magic methods.

**Comment by bensquire** [comment]
Thanks @jcupitt!

**Comment by jcupitt** [comment]
PR to add true streaming, so you could (eg.) open an S3 bucket directly:

https://github.com/libvips/libvips/pull/1443
