### ISSUE TITLE
PDF to JPG with pdfload...

### ISSUE THREAD

**Issue by johnvoncolln** [jcupitt/php-vips#71]
I've read about pdfload, but I can't seem to get that to work...
When I try:
```
$image = \Jcupitt\Vips\Image::pdfload("../storage/app/Untitled-1.pdf");
```
I get `VipsOperation: class "pdfload" not found`

Now, this does work, but I'd like to have the options to set dpi:

```
$image = \Jcupitt\Vips\Image::newFromFile("../storage/app/Untitled-1.pdf");
$image->jpegsave("../storage/app/Untitled-10.jpg");
```

What am I doing wrong?

**Comment by jcupitt** [comment]
Hello, I'd guess your libvips was built without PDF support, so it's falling back to load via ImageMagick.

I see:

```
$ vips -l pdfload
          VipsForeignLoadPdfFile (pdfload), load PDF with libpoppler (.pdf), priority=0, is_a, get_flags, get_flags_filename, header, load
```

**Comment by jcupitt** [comment]
Sorry, rebuilding libvips is probably the simplest.

It has a plugin system, so you could make a pdfload plugin for it, but it would need a bit of programming.

**Comment by johnvoncolln** [comment]
Gotcha - Last question if you don't mind:  I originally built it from the source tarball because there's only an older version available through apt-get (ubuntu 16.4).  Do I need to delete the old version in my home directory?  And what about in /usr/local ?

**Comment by jcupitt** [comment]
You can `make uninstall` and it should remove it, assuming you have the build area still. 

You can also just install a newer version over the top. Old programs will still run, newer programs will see the latest version.

Check the output of configure and make sure pdf is listed as a "yes". You'll need to install `libpopper-glib-dev`, I think, for pdf support.

**Comment by johnvoncolln** [comment]
Thanks - rebuilding now...  

Am I correct in assuming that if you use `newFromFile` method on a PDF file, that it's just going to use the defaults from `pdfload`?

**Comment by jcupitt** [comment]
Yes, that's right. `newFromFile` searches for the highest-priority loader which recognises the file.
