### ISSUE TITLE
VipsOperation: class "thumbnail" not found

### ISSUE THREAD

**Issue by Atsyn** [jcupitt/php-vips#73]
PHP Version 7.2.7-1+ubuntu16.04.1+deb.sury.org+1

PHP extension: https://github.com/jcupitt/php-vips-ext
Vips headers version | 8.2.2
Vips library version | 8.2.2

Last version current library installed via composer.
"name": "jcupitt/vips",
"version": "v1.0.2",

Code:
```
        $originalImage = Vips\Image::newFromFile($temporaryPath);
        if (self::MAX_SIZE < $originalImage->width || self::MAX_SIZE < $originalImage->height) {
            $aspectRatio = $originalImage->width / $originalImage->height;
            if (1 === $aspectRatio) {//square
                $width = self::MAX_SIZE;
                $height = self::MAX_SIZE;
            } else if (1 < $aspectRatio) {//landscape
                $width = self::MAX_SIZE;
                $height = self::MAX_SIZE / $aspectRatio;
            } else {//portrait
                $width = self::MAX_SIZE * $aspectRatio;
                $height = self::MAX_SIZE;
            }
            $image = Vips\Image::thumbnail($temporaryPath, $width, ['height' => $height]);
            $image->writeToFile($temporaryPath);
        }
```

And result - exception: https://monosnap.com/file/MgN2GBH8gag8FN3SR8mPjrVjOmR1mp

I was compared the code in the git and in the composer and find that code a bit difference. It's strange...

**Comment by jcupitt** [comment]
Hello @Atsyn,

Your libvips is too old, unfortunately -- `thumbnail` was added in 8.5. 

Is this a libvips from your package manager? You'll probably need to either update your OS or compile your own libvips from source. It's not difficult to build -- there are some notes here:

https://jcupitt.github.io/libvips/install.html#building-libvips-from-a-source-tarball

You can see what's changed in the `CHANGELOG`:

https://github.com/jcupitt/php-vips/blob/master/CHANGELOG.md

1.0.2 is the tagged version for composer, but git master is 1.0.3. It has a few small improvements. We should probably make 1.0.3 official and start work on 1.0.4.

**Comment by Atsyn** [comment]
Thanks. We updated the library and the problem is gone!
