### ISSUE TITLE
thumbnail as per width specific not working

### ISSUE THREAD

**Issue by akwatra** [jcupitt/php-vips#75]
tried with a thumbnail - not able to fix width and height,

$image = Vips\Image::thumbnail($filename, 200, ['height' => 200]);
$image = Vips\Image::thumbnail($filename, 100,['width' => 100]);

not able to with specific proportion to width wise, as this is working height wise even i mention option width and after filename param always considered as min-height

How can I achieve following with above params pass to method?
 need thumbnail w=100 and proportion as height 
thumbnail - 100wx100h  etc.

**Comment by jcupitt** [comment]
Hello, do you want to fix the width at 100 and let the height float? Just give the width and don't specify a height.

If you want to resize to an exact size and break the aspect ratio, give a height as well and set `size` to `force`.

**Comment by akwatra** [comment]
Okay! It works like this: $image = Vips\Image::thumbnail($filename, 200,['height' => 200,'width' => 100, 'size' => 'force']);
otherwise take care of width or height propotion as per more size side in image.

**Comment by jcupitt** [comment]
The first 200 sets width, so you don't need to set it again. Try:

```php
$image = Vips\Image::thumbnail($filename, 100,['height' => 200, 'size' => 'force']);
```

Otherwise ... looks good!

**Comment by jcupitt** [comment]
Hello, try:

```
vipsthumbnail *.jpg --size 200x200<
```

**Comment by akwatra** [comment]
Hi,
/test $ vipsthumbnail *.jpeg --size 200x200<
bash: syntax error near unexpected token `newline'

**Comment by jcupitt** [comment]
Yes, for bash you need to put quotes around the argument or it'll think you're doing IO redirection.

```
vipsthumbnail *.jpg --size "200x200<"
```

**Comment by akwatra** [comment]
Hi,
vipsthumbnail *.jpg --size "200x200<"
in case of false condition thumbnail generated of actual images size with prefix = "tn_"
seems there is bug, as it should not generate if condition false, ex: width not less than 200px

**Comment by jcupitt** [comment]
It always generates the output file -- the `<` just stops the resize stage.
