### ISSUE TITLE
Sending to Browser

### ISSUE THREAD

**Issue by jarodium** [jcupitt/php-vips#77]
Hello 

How do you send the file to browser output?
is it WriteToBuffer or we can write to file with php://output?

**Comment by jcupitt** [comment]
Hello @jarodium, you can get a string version of your image with `writeToBuffer` and then send that to the browser in any way you like.

If you only want a JPG image, there's also `jpegsave_mime()`, which will write a jpg image with a MIME header to stdout. You'd need to arrange to connect stdout to the user somehow.
