### ISSUE TITLE
document magic methods

### ISSUE THREAD

**Issue by jcupitt** [jcupitt/php-vips#8]
write some py to generate docs for all our magic methods, see

https://www.phpdoc.org/docs/latest/references/phpdoc/tags/method.html

**Comment by jcupitt** [comment]
See https://github.com/jcupitt/php-vips/blob/dev/examples/generate_phpdoc.rb

Sample output https://github.com/jcupitt/php-vips/blob/dev/examples/docs.php

TODO

- [ ] add magic properties as well
- [ ] add constants
- [ ] we need to paste this into `src/Image.php`, or arrange for it to be included ... if we include it, will phpdoc still work?

**Comment by koenpunt** [comment]
You probably want the generator to be in php, if possible.

**Comment by jcupitt** [comment]
Unfortunately the generator needs more introspection than `php-vips-ext` allows, so it has to be Ruby or Python. 

The alternative would be to rewrite the generator in C and put it inside the binary extension.

**Comment by koenpunt** [comment]
> Unfortunately the generator needs more introspection

I was expecting that. But it would be a shame if Ruby becomes a dependency to successfully build the source.

**Comment by jcupitt** [comment]
It would only be needed to regenerate the magic method docs, which will only need updating on a release. It would just be a maintainer thing. 

Let's prototype in Ruby and reimplement in C once it's all nailed down.

**Comment by kleisauke** [comment]
Few improvements:

`project` and `profile` method are incorrectly generated:
https://github.com/jcupitt/php-vips/blob/dev/src/auto_docs.php#L85-L88
(return can be array only)

`extract_area` is generated twice:
https://github.com/jcupitt/php-vips/blob/dev/src/auto_docs.php#L109-L112

By the way,
You could make a empty class in `auto_docs.php` lets say: 
```php
class GeneratedDocs {

}
```

and extend it from the image class:
```php
class Image extends GeneratedDocs implements \ArrayAccess
```

This ensures that modern PHP IDE's can autocomplete (I'm using PhpStorm):
![results extendsdoc](https://cloud.githubusercontent.com/assets/12746591/19429350/8b1097ba-944f-11e6-9ed3-9b7e5c739065.png)

And it looks like a `@method` tag must be on 1 line:
![docs](https://cloud.githubusercontent.com/assets/12746591/19429409/df42eb26-944f-11e6-8255-c38da722c32a.png)
(try to increase the limit of text wrapping to 120 (or disable text wrapping) and change `integer` to `int` type.)

**Comment by jcupitt** [comment]
Ah that makes sense. Thank you for testing this.

I've fixed it up, but now it's not autoloading. I see:

```
$ vendor/bin/phpunit
PHPUnit 5.5.4 by Sebastian Bergmann and contributors.

....
Fatal error: Class 'Jcupitt\Vips\AutoDocs' not found in /home/john/GIT/php-vips/src/Image.php on line 410
```

`Image` can't find the `AutoDocs` class for some reason.

**Comment by kleisauke** [comment]
@jcupitt Unit tests are failing because there's no `namespace Jcupitt\Vips;` in `AutoDocs.php`.

**Comment by jcupitt** [comment]
Of course, I'm an idiot with PHP. All seems to pass now, and the `phpdoc` output is looking better too!

OK to close this issue?

**Comment by jcupitt** [comment]
Ooop, sorry, forgot the one-line issue, I'll fix that too. Though of course that'll make `phpcs` complain.

**Comment by jcupitt** [comment]
OK, line breaks removed. Thank you for fixing all this for me, @kleisauke!

**Comment by jcupitt** [comment]
Typo in generate_phpdoc.rb fixed, thanks.

**Comment by kleisauke** [comment]
@jcupitt No problem! 

For constants: 
We could use something like this model: https://gist.github.com/kleisauke/d6f54acec93ab9b66645c68520ebb0d9
(In this example we only have to generate `Jcupitt\Vips\Enum\VipsColourSpace` automatically without touching the `Image.php` or `AutoDocs.php`)

For validation (like real enums) we could use this: http://stackoverflow.com/a/254543/1480019

There is also a native extension called `SplEnum` but that requires installing an extra extension and `SPL Types` are experimental.

For magic properties:
I think we should also generate them automatically (with `generate_phpdoc.rb`). Example output:
```php
/**
 * @property $width Image width in pixels.
 * @property $height Image height in pixels.
 */
```

**Comment by jcupitt** [comment]
Can we add the enum docs to a single file, or do we need a separate file for each enum? A single file would be more convenient. 

I'll see if I can get a list of all properties somehow.

**Comment by kleisauke** [comment]
Auto-loaders will not find a class that doesn't has his own dedicated file, so multiple classes in a single file is not recommend. See: http://stackoverflow.com/questions/29033625/is-it-possible-use-multiple-classes-under-the-same-namespace-in-the-same-file

However, we could add all enums to a single file (thus in a single class). See: https://gist.github.com/kleisauke/8888471459e193cf93ff25d4794dc6ba

**Comment by jcupitt** [comment]
It now generates @property tags too. This is at the end of AutoDocs.php:

```
 * @property string $nickname Class nickname
 * @property string $description Class description
 * @property integer $width Image width in pixels
 * @property integer $height Image height in pixels
 * @property integer $bands Number of bands in image
 * @property BandFormat $format Pixel format in image
 * @property Coding $coding Pixel coding
 * @property Interpretation $interpretation Pixel interpretation
 * @property float $xres Horizontal resolution in pixels/mm
 * @property float $yres Vertical resolution in pixels/mm
 * @property integer $xoffset Horizontal offset of origin
 * @property integer $yoffset Vertical offset of origin
 * @property string $filename Image filename
 * @property string $mode Open mode
 * @property bool $kill Block evaluation on this image
 * @property DemandStyle $demand Preferred demand style for this image
 * @property integer $sizeof_header Offset in bytes from start of file
 * @property string $foreign_buffer Pointer to foreign pixels
```

I'll have a look at enums next,

**Comment by jcupitt** [comment]
Argh, there are 35 enums, we need to generate 35 files. We could have a single `Constants` class, as you nicely describe, but that seems a bit ugly. 

The enums are generated now, I'll try linking them to the other docs.

**Comment by kleisauke** [comment]
@jcupitt `@property` tags and generated enums looks nice!

Few comments:
- `-` is not allowed in a const name. `-` is interpreted as an expression. We could strip the `-` or convert it to a `_` (underscore).

- Test PHP script:
```php
echo gettype($image->format).PHP_EOL;
echo gettype($image->coding).PHP_EOL;
echo gettype($image->interpretation).PHP_EOL;
```
returns all integers and not strings. Now this compare fails (to detect if the pixel values in a image is 16-bit):
```php
$image->interpretation == Interpretation::RGB16 || $image->interpretation == Interpretation::GREY16;
```
Should we return `->interpretation`, `->coding` and `->format` as string in `php-vips-ext` and keep these enums or should we change the constants in `BandFormat`, `Interpretation`, `Coding` to integers to ensure that we can compare things? (Could not test the type of `->demand` because of this error `vips_image_get: field "demand" not found`)
- I think it's nicer to put the enums in a directory (e.g. `Enum`) and change the namespace of the enums to that directory (e.g. `namespace Jcupitt\Vips\Enum`) to use them in the `AutoDocs.php` we can put:
```php
use Jcupitt\Vips\Enum\Interpretation;
use Jcupitt\Vips\Enum\BandFormat;
use Jcupitt\Vips\Enum\DemandStyle;
use Jcupitt\Vips\Enum\Coding;
```
on the top of the PHP file.
- We have now `ImageAutodoc` and `AutoDocs` with the same content, which one should we keep?

**Comment by jcupitt** [comment]
OK, I've fixed it up a bit.

* swap `-` for `_` in enum names
* enums in a sub namespace
* removed AutoDocs
* linked Image to the various enums, I think

I'm not sure what to do about strings versus ints for enum values. We should probably use ints everywhere in the php layer, but allow strings as a shortcut in `php-vips-ext`.

**Comment by kleisauke** [comment]
@jcupitt  Few comments:

PhpStorm complains that it expected a class as input. See:
![phpstorm expected](https://cloud.githubusercontent.com/assets/12746591/19477623/61d90652-953f-11e6-959a-e10843cbc335.png)

Maybe we should drop all the class parameters in the `ImageAutodoc` class (and replace them for example with `string` type). And put a `@see` tag for available formats, for example:
```php
/**
 * @method Image relational(Image $right, string $relational, array $options = []) Relational operation on two images.
 *         @see OperationRelational for available formats for the `$relational` parameter.
 */
```

- The swap `-` for `_` in enum names happens also in the enum values.
- The enums are now in a sub namespace. We can put them in a directory named `Enum` because  classes should be stored in folders according to their namespaces.

**Comment by jcupitt** [comment]
OK, I think I've done this. There's now an `Enum` directory with these files in, `@see` lines are generated for enum references, and enum values don't have the `-`, `_` swap.

We still have the problem of `$image->format` being an integer.

**Comment by kleisauke** [comment]
@jcupitt This looks really nice! When I have some spare time, I can implement these enums in the `Image` class.

One comment:
PhpStorm still complains that `array(Image, Image)`, `array(float)` and `array(Image)` isn't valid.

In order to solve this, I think this would be the best:
`array(float)` -> `array` (or `float[]`)
`array(Image, Image)` -> `array`
`array(Image)` -> `Image[]` (or `array`)

You can then add a note (on the top of the PHPDoc) for the `array|float` parameter and clarifications for the return array of the `project` and `profile` method. For example:
```php
/**
 * Autodocs for the Image class.
 * @category  Images
 * @package   Jcupitt\Vips
 * @author    John Cupitt <jcupitt@gmail.com>
 * @copyright 2016 John Cupitt
 * @license   https://opensource.org/licenses/MIT MIT
 * @version   Release:0.1.2
 * @link      https://github.com/jcupitt/php-vips
 *
 * NOTE:
 * When there's a `array|float` defined as parameter value; then you can supply this
 * value as an a float, or as an array of floats. libvips types are automatically wrapped and unwrapped.
 * The binding looks at the type of argument required by the operation and converts the value you supply, when it can.
 *
 * For example, you can write:
 * ```php
 * // Constant is used for all image bands.
 * $result = $image->linear(1, 3);
 * $result = $image->linear(12.4, 13.9);
 *
 * // One array element is used for each band.
 * $result = $image->linear([1, 2, 3], [4, 5, 6]);
 * $result = $image->linear(1, [4, 5, 6]);
 * ```
 *
 * @method static Image sum(Image[] $in, array $options = []) Sum an array of images.
 * @method Image linear(array|float $a, array|float $b, array $options = []) Calculate (a * in + b).
 * @method Image relational_const(array|float $c, string $relational, array $options = []) Relational operations against a constant.
 *     @see OperationRelational for possible values for $relational
 * @method Image remainder_const(array|float $c, array $options = []) Remainder after integer division of an image and a constant.
 * @method Image boolean_const(array|float $c, string $boolean, array $options = []) Boolean operations against a constant.
 *     @see OperationBoolean for possible values for $boolean
 * @method Image math2_const(array|float $c, string $math2, array $options = []) Pow( @in, @c ).
 *     @see OperationMath2 for possible values for $math2
 * @method array project(array $options = []) Find image projections.
 *     Returns array with: [
 *          'columns' => @type Image|float The sum of every column of pixels (output depends on the input format),
 *          'rows' => @type Image|float The sum of every row of pixels (output depends on the input format)
 *     ];
 * @method array profile(array $options = []) Find image profiles.
 *     Returns array with: [
 *          'columns' => @type Image First non-zero pixel in column,
 *          'rows' => @type Image First non-zero pixel in row
 *     ];
 * @method array|float getpoint(integer $x, integer $y, array $options = []) Read a point from an image.
 * @method static Image arrayjoin(Image[] $in, array $options = []) Join an array of images.
 * @method Image bandjoin_const(array|float $c, array $options = []) Append a constant band to an image.
 * @method Image affine(array|float $matrix, array $options = []) Affine transform of an image.
 * @method Image draw_rect(array|float $ink, integer $left, integer $top, integer $width, integer $height, array $options = []) Paint a rectangle on an image.
 * @method Image draw_mask(array|float $ink, Image $mask, integer $x, integer $y, array $options = []) Draw a mask on an image.
 * @method Image draw_line(array|float $ink, integer $x1, integer $y1, integer $x2, integer $y2, array $options = []) Draw a line on an image.
 * @method Image draw_circle(array|float $ink, integer $cx, integer $cy, integer $radius, array $options = []) Draw a circle on an image.
 * @method Image draw_flood(array|float $ink, integer $x, integer $y, array $options = []) Flood-fill an area.
 */
```

About the problem of `$image->format`. We could solve this with an lookup array, for example (untested):
```php
public function __get(string $name)
{
    $result = vips_image_get($this->_image, $name);
    self::_errorIsArray($result);

    $result = self::_wrap($result);

    $fix = [
        'format' => [
            -1 => BandFormat::NOTSET,
            0 => BandFormat::UCHAR,
            1 => BandFormat::CHAR,
            2 => BandFormat::USHORT,
            3 => BandFormat::SHORT,
            4 => BandFormat::UINT,
            5 => BandFormat::INT,
            6 => BandFormat::FLOAT,
            7 => BandFormat::COMPLEX,
            8 => BandFormat::DOUBLE,
            9 => BandFormat::DPCOMPLEX,
        ],
    ];


     return isset($fix[$name][$result]) ? $fix[$name][$result] : $result;
}
```

This will convert a enum integer to the right enum string. But I think this is a bit ugly.. 👎
The right approach should be fixing this in `php-vips-ext`.

**Comment by jcupitt** [comment]
Hi again, thanks again for reviewing this.

OK, I've tried again. It now looks like this:

```
 * @method array profile(array $options = []) Find image profiles.
 *     Return array with: [
 *         'columns' => @type Image First non-zero pixel in column.
 *         'rows' => @type Image First non-zero pixel in row.
 *     ];
 * @method Image linear(float[]|float $a, float[]|float $b, array $options = []) Calculate (a * in + b).
 * @method Image colourspace(string $space, array $options = []) Convert to a new colourspace.
 *     @see Interpretation for possible values for $space
```

https://github.com/jcupitt/php-vips/commit/e9cf7f7f12d5f62d99e3157b23e9c6a7d51bb90a

The text at the top of `Image.php` already talks about the magic float -> array conversions. Perhaps it can be improved. 

https://github.com/jcupitt/php-vips/blob/dev/src/Image.php#L292

Yes, I'll look into why `php-vips-ext` is making a LONG.

**Comment by kleisauke** [comment]
No problem, I've reviewed it again and could not find any problems! There are only some unused `use` statements in `ImageAutodoc` but that doesn't impact performance.

**Comment by jcupitt** [comment]
I think I found it: https://github.com/jcupitt/php-vips-ext/commit/333b22d73b7e252625e2891712ff49c4d5ae80b2

`$image->interpretation` should now be a string, woo!

Thanks for reviewing again, I think we can close. I'll add a test for string returns for enums.
